export const dataKeys = {
  Pédiatrie: [
    "Alimentation",
    "Allergologie",
    "Asthme du nourrisson",
    "Colite du nourrisson",
    "Enurésie primaire",
    "Fontanelle",
    "Mycoses",
    "Otites",
    "RGO",
    "Vaccination",
    "Vitamines",
  ],
  Dermatologie: [
    "Acné",
    "Cicatrice chéloïde",
    "Dermatite atopique",
    "Dermite séborrhéique du nourrisson",
    "Dyshidrose",
    "Hyperhidrose",
    "Kératodermie",
    "Mycoses",
    "Protection solaire",
    "Prurigo",
    "Psoriasis",
    "Rosacée",
    "Tâches cafés",
    "Verrue",
  ],
  Gynécologie: [
    "Cancers gynécologiques",
    "Contraception",
    "Douleurs pelviennes",
    "Dysménorrhée",
    "Endométriose",
    "Infertilité",
    "Mastodynie",
    "Mycose vaginale récidivante",
  ],
  Mère: ["Césarienne", "Grossesse", "Montée de lait"],
  Autre: ["Imagerie", "Odontologie", "Ophtalmologie", "HTA", "Epaule"],
};
